-- Disposable local database only. Validates canonical Product cutover identity, images, and storage governance.
begin;

create temp table cutover_test_results (
  area text not null,
  test_name text not null,
  passed boolean not null,
  primary key (area, test_name)
) on commit drop;

create or replace function public.cutover_record_result(p_area text, p_test_name text)
returns void
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into cutover_test_results(area, test_name, passed)
  values (p_area, p_test_name, true)
  on conflict (area, test_name) do update set passed = excluded.passed;
end;
$$;

do $$
declare
  v_owner uuid := '94000000-0000-4000-8000-000000000001';
  v_admin uuid := '94000000-0000-4000-8000-000000000002';
  v_staff uuid := '94000000-0000-4000-8000-000000000003';
  v_viewer uuid := '94000000-0000-4000-8000-000000000004';
  v_category uuid;
  v_product_id uuid;
  v_product_code text;
  v_master_product_id text;
  v_variant_id uuid;
  v_sku text;
  v_global_sku text;
  v_master_variant_id text;
  v_image_id uuid;
  v_rows integer;
begin
  insert into auth.users(id, email)
  values
    (v_owner, 'cutover-owner@example.test'),
    (v_admin, 'cutover-admin@example.test'),
    (v_staff, 'cutover-staff@example.test'),
    (v_viewer, 'cutover-viewer@example.test')
  on conflict (id) do nothing;

  insert into public.admin_users(user_id, email, role, display_name, is_active)
  values
    (v_owner, 'cutover-owner@example.test', 'owner', 'Cutover Owner', true),
    (v_admin, 'cutover-admin@example.test', 'admin', 'Cutover Admin', true),
    (v_staff, 'cutover-staff@example.test', 'staff', 'Cutover Staff', true),
    (v_viewer, 'cutover-viewer@example.test', 'viewer', 'Cutover Viewer', true)
  on conflict (user_id) do update
  set role = excluded.role,
      is_active = true,
      display_name = excluded.display_name;

  insert into public.product_categories(name, code, product_type, created_by_user_id)
  values ('Cutover Physical', 'CUTOVER-PHYSICAL', 'PHYSICAL', v_owner)
  returning id into v_category;

  insert into public.products(category_id, name, description, product_type, created_by_user_id)
  values (v_category, 'Cutover Product', 'Identity generated by trigger', 'PHYSICAL', v_owner)
  returning id, product_code, master_product_id into v_product_id, v_product_code, v_master_product_id;

  if v_master_product_id !~ '^MP-[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}$' then
    raise exception 'master_product_id format mismatch: %', v_master_product_id;
  end if;
  perform public.cutover_record_result('IDENTITY', 'master_product_id generated server-side');

  if v_product_code !~ '^PRD-[0-9]{6}-[0-9A-F]{6}$' then
    raise exception 'product_code format mismatch: %', v_product_code;
  end if;
  perform public.cutover_record_result('IDENTITY', 'product_code generated server-side');

  insert into public.products(
    category_id,
    name,
    description,
    product_type,
    master_product_id,
    product_code,
    created_by_user_id
  )
  values (
    v_category,
    'Client Supplied Identity Product',
    'Client identifiers must be replaced',
    'PHYSICAL',
    'MP-CLIENT-SUPPLIED',
    'CLIENT-PRODUCT-CODE',
    v_owner
  )
  returning product_code, master_product_id into v_sku, v_master_variant_id;
  if v_sku = 'CLIENT-PRODUCT-CODE' or v_master_variant_id = 'MP-CLIENT-SUPPLIED' then
    raise exception 'client product identity accepted';
  end if;
  perform public.cutover_record_result('IDENTITY', 'client product identity ignored on insert');

  begin
    update public.products set product_code = 'PRD-260814-ABCDEF' where id = v_product_id;
    raise exception 'product_code mutation accepted';
  exception when insufficient_privilege then
    perform public.cutover_record_result('IDENTITY', 'product_code immutable');
  end;

  insert into public.product_variants(product_id, size, color, selling_price, unit_cost, created_by_user_id)
  values (v_product_id, 'Medium', 'Washed Black', 1200, 600, v_owner)
  returning id, sku, global_sku into v_variant_id, v_sku, v_global_sku;

  if v_sku <> v_product_code || '-WASHEDBL-MEDIUM' then
    raise exception 'sku token format mismatch: %', v_sku;
  end if;
  if v_global_sku !~ '^GSKU-[0-9]{6}-[0-9A-F]{8}$' then
    raise exception 'global_sku format mismatch: %', v_global_sku;
  end if;
  perform public.cutover_record_result('IDENTITY', 'variant sku and global sku generated server-side');

  insert into public.product_variants(
    product_id,
    size,
    color,
    selling_price,
    unit_cost,
    master_variant_id,
    global_sku,
    sku,
    created_by_user_id
  )
  values (
    v_product_id,
    'Large',
    'Green',
    1300,
    650,
    'MV-CLIENT-SUPPLIED',
    'GSKU-CLIENT-SUPPLIED',
    'CLIENT-SKU',
    v_owner
  )
  returning sku, global_sku, master_variant_id into v_sku, v_global_sku, v_master_variant_id;
  if v_sku <> v_product_code || '-GREEN-LARGE'
    or v_global_sku = 'GSKU-CLIENT-SUPPLIED'
    or v_master_variant_id = 'MV-CLIENT-SUPPLIED' then
    raise exception 'client variant identity accepted: %, %, %', v_sku, v_global_sku, v_master_variant_id;
  end if;
  perform public.cutover_record_result('IDENTITY', 'client variant identity ignored on insert');

  insert into public.product_variants(product_id, size, color, selling_price, unit_cost, created_by_user_id)
  values (v_product_id, 'Medium', 'Washed Black', 1300, 650, v_owner)
  returning sku into v_sku;
  if v_sku <> v_product_code || '-WASHEDBL-MEDIUM-02' then
    raise exception 'sku collision suffix mismatch: %', v_sku;
  end if;
  perform public.cutover_record_result('IDENTITY', 'variant sku collision uses numeric suffix');

  begin
    update public.product_variants set global_sku = 'GSKU-260814-00000000' where id = v_variant_id;
    raise exception 'global_sku mutation accepted';
  exception when insufficient_privilege then
    perform public.cutover_record_result('IDENTITY', 'global_sku immutable');
  end;

  begin
    update public.product_variants set sku = 'DIRECT-SKU' where id = v_variant_id;
    raise exception 'direct sku mutation accepted';
  exception when insufficient_privilege then
    perform public.cutover_record_result('IDENTITY', 'direct sku mutation rejected');
  end;

  perform set_config('request.jwt.claim.sub', v_owner::text, true);
  perform public.override_product_variant_sku(v_variant_id, v_product_code || '-OWNER-OVERRIDE', '', 'owner sku correction');
  perform public.cutover_record_result('IDENTITY', 'owner sku override still works');

  begin
    perform public.override_product_variant_sku(v_variant_id, v_product_code || '-BAD-GLOBAL', 'GSKU-260814-FFFFFFFF', 'global should fail');
    raise exception 'global sku override accepted';
  exception when insufficient_privilege then
    perform public.cutover_record_result('IDENTITY', 'global sku override rejected');
  end;

  perform public.set_product_images_for_product(v_product_id, jsonb_build_array(
    jsonb_build_object('storagePath', 'catalog/cutover/one.webp', 'publicUrl', 'https://example.test/one.webp'),
    jsonb_build_object('storagePath', 'catalog/cutover/two.webp', 'publicUrl', 'https://example.test/two.webp')
  ));

  select id into v_image_id
  from public.product_images
  where product_id = v_product_id and position = 0 and is_primary = true;
  if v_image_id is null then
    raise exception 'fallback primary image not assigned to position zero';
  end if;
  perform public.cutover_record_result('IMAGES', 'first active image is fallback primary');

  perform public.set_product_images_for_product(v_product_id, jsonb_build_array(
    jsonb_build_object('id', (select id from public.product_images where product_id = v_product_id and position = 0), 'storagePath', 'catalog/cutover/one.webp', 'publicUrl', 'https://example.test/one.webp', 'isPrimary', false),
    jsonb_build_object('id', (select id from public.product_images where product_id = v_product_id and position = 1), 'storagePath', 'catalog/cutover/two.webp', 'publicUrl', 'https://example.test/two.webp', 'isPrimary', true)
  ));

  if not exists (select 1 from public.product_images where product_id = v_product_id and position = 1 and is_primary = true and storage_path = 'catalog/cutover/two.webp') then
    raise exception 'explicit primary image did not remain independent from position';
  end if;
  perform public.cutover_record_result('IMAGES', 'explicit primary is independent from order');

  perform public.set_product_images_for_product(v_product_id, jsonb_build_array(
    jsonb_build_object('id', (select id from public.product_images where product_id = v_product_id and position = 1), 'storagePath', 'catalog/cutover/two.webp', 'publicUrl', 'https://example.test/two.webp')
  ));

  if not exists (select 1 from public.product_images where product_id = v_product_id and position = 0 and is_primary = true and storage_path = 'catalog/cutover/two.webp') then
    raise exception 'primary was not promoted after archive/reorder';
  end if;
  perform public.cutover_record_result('IMAGES', 'primary promotes to next ordered image');

  begin
    update public.product_images
    set is_primary = false
    where product_id = v_product_id and position = 0;
    set constraints all immediate;
    raise exception 'primary removal accepted';
  exception when check_violation then
    perform public.cutover_record_result('IMAGES', 'one primary rule enforced');
  end;
  set constraints all deferred;

  begin
    insert into public.product_images(product_id, storage_path, position, is_primary)
    values (v_product_id, 'catalog/cutover/duplicate-position.webp', 0, false);
    raise exception 'duplicate active image position accepted';
  exception when unique_violation then
    perform public.cutover_record_result('IMAGES', 'duplicate active position rejected');
  end;

  begin
    perform public.set_product_images_for_product(v_product_id, jsonb_build_array(
      jsonb_build_object('storagePath', 'catalog/cutover/1.webp'),
      jsonb_build_object('storagePath', 'catalog/cutover/2.webp'),
      jsonb_build_object('storagePath', 'catalog/cutover/3.webp'),
      jsonb_build_object('storagePath', 'catalog/cutover/4.webp'),
      jsonb_build_object('storagePath', 'catalog/cutover/5.webp'),
      jsonb_build_object('storagePath', 'catalog/cutover/6.webp'),
      jsonb_build_object('storagePath', 'catalog/cutover/7.webp')
    ));
    raise exception 'seventh image accepted';
  exception when check_violation then
    perform public.cutover_record_result('IMAGES', 'seventh active image rejected');
  end;
end
$$;

do $$
begin
  if has_function_privilege('anon', 'public.generate_product_code_candidate()', 'EXECUTE') then
    raise exception 'anon can execute product code generator';
  end if;
  if has_function_privilege('authenticated', 'public.generate_product_code_candidate()', 'EXECUTE') then
    raise exception 'authenticated can execute product code generator directly';
  end if;
  if has_function_privilege('public', 'public.assign_product_canonical_identity()', 'EXECUTE') then
    raise exception 'PUBLIC can execute product identity trigger function';
  end if;
  if has_function_privilege('anon', 'public.set_product_images_for_product(uuid,jsonb)', 'EXECUTE') then
    raise exception 'anon can execute image RPC';
  end if;
  if not has_function_privilege('authenticated', 'public.set_product_images_for_product(uuid,jsonb)', 'EXECUTE') then
    raise exception 'authenticated cannot execute image RPC';
  end if;
  perform public.cutover_record_result('SECURITY', 'function grants are minimum required');
end
$$;

set local role authenticated;
select set_config('request.jwt.claim.sub', '94000000-0000-4000-8000-000000000002', true);
insert into storage.objects(bucket_id, name, owner)
values ('catalog-images', 'trry-webapp/94000000-0000-4000-8000-000000000002/admin.webp', '94000000-0000-4000-8000-000000000002');
select public.cutover_record_result('STORAGE', 'admin can upload catalog object');

do $$
begin
  insert into storage.objects(bucket_id, name, owner)
  values ('catalog-images', 'admin-outside-folder.webp', '94000000-0000-4000-8000-000000000002');
  raise exception 'admin upload outside catalog path accepted';
exception when insufficient_privilege then
  perform public.cutover_record_result('STORAGE', 'object path convention enforced');
end
$$;

select set_config('request.jwt.claim.sub', '94000000-0000-4000-8000-000000000001', true);
insert into storage.objects(bucket_id, name, owner)
values ('catalog-images', 'trry-webapp/94000000-0000-4000-8000-000000000001/owner.webp', '94000000-0000-4000-8000-000000000001');
select public.cutover_record_result('STORAGE', 'owner can upload catalog object');

select set_config('request.jwt.claim.sub', '94000000-0000-4000-8000-000000000003', true);
do $$
begin
  insert into storage.objects(bucket_id, name, owner)
  values ('catalog-images', 'trry-webapp/94000000-0000-4000-8000-000000000003/staff.webp', '94000000-0000-4000-8000-000000000003');
  raise exception 'staff catalog object upload accepted';
exception when insufficient_privilege then
  perform public.cutover_record_result('STORAGE', 'staff upload denied');
end
$$;

select set_config('request.jwt.claim.sub', '94000000-0000-4000-8000-000000000004', true);
do $$
begin
  insert into storage.objects(bucket_id, name, owner)
  values ('catalog-images', 'trry-webapp/94000000-0000-4000-8000-000000000004/viewer.webp', '94000000-0000-4000-8000-000000000004');
  raise exception 'viewer catalog object upload accepted';
exception when insufficient_privilege then
  perform public.cutover_record_result('STORAGE', 'viewer upload denied');
end
$$;
reset role;

select * from cutover_test_results order by area, test_name;
rollback;
