window.TRRY_ADMIN_ENV = window.TRRY_ADMIN_ENV || {
  VITE_SUPABASE_URL: "",
  VITE_SUPABASE_ANON_KEY: "",
  VITE_USE_SUPABASE_DATA: "true",
  VITE_ENABLE_TASK_DOMAIN: "false",
  VITE_ENABLE_WORKBOARD: "false",
  VITE_ENABLE_MY_TASKS: "false",
  VITE_ENABLE_CALENDAR: "false",
  VITE_ENABLE_AUTO_PLAN_TODAY: "false",
};
